export const DEBUGGING_ON = false;

// Info Config
export const INITIAL_CATEGORY_ID = null;
export const INITIAL_ANNOTATION_ID = null;
export const ANNOTATION_EXPANDED = true;

// Paper.js Config
export const CANVAS_RASTER_PREFIX = 'RASTER';
export const CANVAS_ZOOM_FACTOR = 1.2;
export const CANVAS_ZOOM_MIN = 0.01;
export const CANVAS_ZOOM_MAX = 10;
export const CANVAS_PAN_FACTOR = 0.5;

export const CATEGORY_GROUP_PREFIX = 'CATEGORY_GROUP_';
export const ANNOTATION_GROUP_PREFIX = 'ANNOTATION_GROUP_';
export const ANNOTATION_SHAPE_PREFIX = 'ANNOTATION_SHAPE_';
export const ANNOTATION_KEYPOINTS_PREFIX = 'KEYPOINTS_';

export const ANNOTATION_SHAPE_OPACITY = 0.6;

export const TITLE_GROUP_PREFIX = 'TITLE_GROUP';
export const TITLE_FONT_SCALE = 0.025;
export const TITLE_HEIGHT_SCALE = 0.5;

export const TOOLS_BBOX_SCALE_FACTOR = 3;
export const TOOLS_BBOX_INITIAL_COLOR = 'black';

export const TOOLS_BRUSH_SCALE_FACTOR = 3;
export const TOOLS_BRUSH_INITIAL_STROKE_WIDTH = 1;
export const TOOLS_BRUSH_INITIAL_RADIUS = 30;
export const TOOLS_BRUSH_INITIAL_COLOR = 'white';

export const TOOLS_SELECT_INITIAL_TOOLTIP_ON = true;
export const TOOLS_SELECT_INITIAL_HIT_TOLERANCE = 10;
export const TOOLS_SELECT_SCALE_ROUNDED = 5;
export const TOOLS_SELECT_SCALE_TEXT_SHIFT = 40;
export const TOOLS_SELECT_SCALE_FONTSIZE = 15;
export const TOOLS_SELECT_SCALE_INDICATOR_SIZE = 10;
export const TOOLS_SELECT_SCALE_INDICATOR_WIDTH = 2;

export const TOOLS_POLYGON_INITIAL_GUIDANCE = true;
export const TOOLS_POLYGON_INITIAL_MIN_DISTANCE = 2;
export const TOOLS_POLYGON_INITIAL_COMPLETE_DISTANCE = 5;
export const TOOLS_POLYGON_INITIAL_COLOR_AUTO = true;
export const TOOLS_POLYGON_INITIAL_COLOR_RADIUS = 10;
export const TOOLS_POLYGON_INITIAL_STROKE_WIDTH = 1;
export const TOOLS_POLYGON_INITIAL_STROKE_COLOR = 'black';
export const TOOLS_POLYGON_SCALE = 3;

export const TOOLS_WAND_INITIAL_THRESHOLD = 30;
export const TOOLS_WAND_INITIAL_BLUR = 30;

export const TOOLS_DEXTR_INITIAL_PADDING = 50;
export const TOOLS_DEXTR_INITIAL_THRESHOLD = 80;
