DETECTION_MASKS = 'detection_masks'
DETECTION_SCORES = 'detection_scores'
DETECTION_BOXES = 'detection_boxes'
DETECTION_CLASSES = 'detection_classes'
NUM_DETECTIONS = 'num_detections'
output_type_enum = {0: [NUM_DETECTIONS, DETECTION_BOXES, DETECTION_SCORES, DETECTION_CLASSES, DETECTION_MASKS],
                    1: [NUM_DETECTIONS, DETECTION_BOXES, DETECTION_SCORES, DETECTION_CLASSES],
                    2: [DETECTION_BOXES, DETECTION_SCORES, DETECTION_CLASSES]}
